### ISSUE TITLE
Can't load pretrained models

### ISSUE THREAD

**Issue by Patelraj8694** [sony/bigvsan#4]
Hi,

Thank you for the good work. But i am having issues with loading the pretrained models. It gives unpicking error. If you can help out

**Comment by Patelraj8694** [comment]
Sorted out problem

**Comment by TakashiShibuyaSony** [comment]
Thank you for having an interest in our work. It's good that you could resolve the issue by yourself.

**Comment by Patelraj8694** [comment]
Hi, @TakashiShibuyaSony ,thank you for responding, I have a question that can i fine tune this model with whisper data for whisper or distorted speech to normal speech?

**Comment by TakashiShibuyaSony** [comment]
@Patelraj8694 
I've never tried to fine-tune a pretrained BigSAN model, so this is just my quick thought.

Yes, you "can" fine-tune a pretraied model just by preparing audio file lists (like https://github.com/sony/bigvsan/tree/0e60312acbb35039709535924e9d14167931959f/LibriTTS), setting the arguments https://github.com/sony/bigvsan/blob/0e60312acbb35039709535924e9d14167931959f/train.py#L394-L400 regarding the audio file lists, and setting the argument https://github.com/sony/bigvsan/blob/0e60312acbb35039709535924e9d14167931959f/train.py#L402 about the directory for checkpoints. You need to place the pretrained checkpoints there, and fine-tuned model will also be saved in the same directory.

But, I'm guessing that training stability will depend on the size of data.
